export const GET_IMAGES_DATA='getImages'
export const GET_ERROR_DATA='getErrorData'
export const GET_IMAGE_DATA_BY_ID='getImage'
export const DELETE_IMAGE_DATA='deleteImage'
export const DOWNLOAD_IMAGE='downloadImage'
export const NEXT_PAGE_URL='changeUrlToNext'
export const PREVIOUS_PAGE_URL='changeUrlToPrevious'
export const CHANGE_NUMBER_OF_IMAGES='changePageLimit'